### PR TITLE
ext: lib: mgmt: Enabling Zephyr/mynewt-core version of tinycbor

### PR DESCRIPTION
**Pull request by de-nordic**
Changes needed due to overwrite of Zephyr fork of Tinycbor with
mynewt-core version.

Signed-off-by: Dominik Ermel <dominik.ermel@nordicsemi.no>

### CODE REVIEW

**Comment by utzig** [comment]
Is this dependent on the merge of https://github.com/zephyrproject-rtos/tinycbor/pull/11 ?

**Comment by de-nordic** [comment]
> 
> 
> Is this dependent on the merge of [zephyrproject-rtos/tinycbor#11](https://github.com/zephyrproject-rtos/tinycbor/pull/11) ?

It is dependent for Zephyr, as zephyr will not compile if both changes (this and tinycbor) are done at the same time.

**Comment by carlescufi** [comment]
@utzig @sjanc can we merge this?

**Comment by utzig** [comment]
> @utzig @sjanc can we merge this?

I honestly did not understand @de-nordic comment, but I believe you both know what you're doing!

**Comment by carlescufi** [comment]
Thanks! @utzig we are trying to consolidate tinycbor so that it's the same as in mynewt.

**Comment by utzig** [comment]
> I honestly did not understand @de-nordic comment, but I believe you both know what you're doing!

To be clear, this obviously only affects Zephyr, so there's no point in saying it. What was not clear to me is where the changes that add tinycbor from Mynewt on Zephyr are, but you both sure of the change, and I don't see anything wrong with it either!

**Pull request merged**
