### PR TITLE
Multi-image upload

### PR DESCRIPTION
**Pull request by de-nordic**
The PR contains three PRs that provide multi-image upload and list.
These are three top commits.

Depends on:
 - https://github.com/apache/mynewt-mcumgr/pull/133
 - https://github.com/apache/mynewt-mcumgr/pull/134
 
 Configured by K config provided with (can be added later):
  - https://github.com/zephyrproject-rtos/zephyr/pull/37903

Would be nice to have:
 - https://github.com/zephyrproject-rtos/zephyr/pull/37920

### CODE REVIEW

**Comment by de-nordic** [comment]
@nvlsianpu @hakonfam @mlaz @utzig Please review.

**Comment by de-nordic** [comment]
> 
> 
> Thanks I'm wondering if it would not be better to have a configuration to protect the first slot of the second image against upload when it's activated

What do you mean by that? You always upload to the secondary slot and mcuboot shuffles slots.

**Comment by kurddt** [comment]
> What do you mean by that? You always upload to the secondary slot and mcuboot shuffles slots.

True but unless I miss-understand https://github.com/apache/mynewt-mcumgr/blob/363eebd69f752a9d6fdf7187e5de546ad10940ba/cmd/img_mgmt/port/zephyr/src/zephyr_img_mgmt.c#L168. direct uploading an image to slot 2 (primary slot of the second image) is allowed

**Comment by de-nordic** [comment]
Yes, but direct upload is different thing.

**Review by sjanc — APPROVED** [review]
looks OK to me

nitpick: could consistently use switch-case vs if-elseif-else in functions

**Review by nvlsianpu — APPROVED** [review]

**Review by kurddt — APPROVED** [review]

**Comment by de-nordic** [comment]
> 
> 
> looks OK to me
> 
> nitpick: could consistently use switch-case vs if-elseif-else in functions

Will have to work on style.

**Pull request merged**
