### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by alokprinc**
Version has been updated from 1.7 to 1.12

### CODE REVIEW

**Comment by utzig** [comment]
@alokprinc The version is correct, but maybe you could make the commit message a bit more meaningful for someone reading a git log, maybe something like "README: bump required go version"?

**Comment by alokprinc** [comment]
Should I write commit message as u suggested.  " README : bump required go version"
Or How about
"README : minimum required go version changed to 1.12"

**Comment by alokprinc** [comment]
current version is 1.13 can i update it?

**Comment by utzig** [comment]
> Should I write commit message as u suggested. " README : bump required go version"
> Or How about
> "README : minimum required go version changed to 1.12"

Yep, looks OK.

> current version is 1.17 can i update it?

No, it requires 1.12, not everyone will have the latest version.

**Comment by utzig** [comment]
Fixed by #145

**Pull request closed without merging**
