### PR TITLE
zephyr: fix initialization of file struct

### PR DESCRIPTION
**Pull request by niclas-ats**
Fixes issue #116

### CODE REVIEW

**Review by de-nordic — APPROVED** [review]
The code looks ok. Please add some lines of description to commit, e.g.
"With release of Zephyr 2.5 the fs_file_t structure requires initialization prior to first usage"

**Comment by de-nordic** [comment]
@utzig @nvlsianpu Can you take a look?

**Comment by de-nordic** [comment]
@niclas-ats Can you also please sign-off your commit?

**Review by nvlsianpu — APPROVED** [review]

**Comment by nvlsianpu** [comment]
@utzig Please merge if you can.

**Review by utzig — APPROVED** [review]

**Pull request merged**
